# Generated by Django 2.1.3 on 2018-11-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='favorite',
            field=models.BooleanField(default=True),
        ),
    ]
