# Generated by Django 2.1.3 on 2018-11-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_hero_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
