# Generated by Django 2.1.3 on 2018-11-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_auto_20181128_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
