# Generated by Django 2.1.3 on 2018-11-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_auto_20181130_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hero',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
