# Generated by Django 2.1.3 on 2018-11-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0006_auto_20181130_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='test',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
