# Generated by Django 2.1.3 on 2018-11-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_hero_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='test',
            new_name='teste',
        ),
    ]
