# Generated by Django 2.1.3 on 2018-11-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0008_auto_20181130_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='teste',
        ),
        migrations.AlterField(
            model_name='hero',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
