# Generated by Django 2.1.3 on 2018-11-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0009_auto_20181130_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
