# Generated by Django 2.1.3 on 2018-11-30 21:32

import buckets.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0011_auto_20181130_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='photo',
            field=buckets.fields.S3FileField(upload_to='media'),
        ),
    ]
