# Generated by Django 2.1.3 on 2018-11-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0012_auto_20181130_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='photo',
            field=models.TextField(),
        ),
    ]
