# Generated by Django 2.1.3 on 2018-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0013_auto_20181130_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
